package Utilities;

public class codes {

	public static final byte LOGINREQUEST = 0;
    public static final byte LOGINRESPONSE = 1;
    public static final byte REGISTERREQUEST = 2;
    public static final byte REGISTERRESPONSE = 3;
    public static final byte UPLOADREQUEST = 4;
    public static final byte UPLOADRESPONSE = 5;
    public static final byte DOWNLOADREQUEST = 6;
    public static final byte DOWNLOADRESPONSE = 7;
    public static final byte SHAREREQUEST = 8;
    public static final byte SHARERESPONSE = 9;
    public static final byte UNSHAREREQUEST = 10;
    public static final byte UNSHARERESPONSE = 11;
    public static final byte DELETEREQUEST = 12;
    public static final byte DELETERESPONSE = 13;
    public static final byte GETALLFILESREQUEST = 14;
    public static final byte GETALLFILESRESPONSE = 15;
    public static final byte FILEDATA = 16;
    public static final byte FILEDATAACK = 17;
    public static final byte GETSHAREDFILESREQUEST = 18;
    public static final byte GETSHAREDFILESRESPONSE = 19;
    public static final byte ACK = 52;
    public static final byte OK = 53;
    public static final byte ERR = 54;
    public static final byte QUIT = 100;
    public static final byte NOSUCHFILE = 101;
    public static final byte NOSUCHUSER = 102; 
    public static final byte USEREXISTS = 103; 
    public static final byte LOGINSUCCESS = 104;
    public static final byte LOGINFAIL = 105;  
    public static final byte REGISTERSUCCESS = 106; 
    public static final byte REGISTERFAIL = 107; 
    public static final byte UPLOADSUCCESS = 108; 
    public static final byte UPLOADFAIL = 109; 
    public static final byte DOWNLOADSUCCESS = 110; 
    public static final byte DOWNLOADFAIL = 111; 
    public static final byte FILEEXISTS = 112; 
    public static final byte SHARESUCCESS = 113; 
    public static final byte SHAREFAIL = 114; 
    public static final byte UNSHARESUCCESS = 115; 
    public static final byte UNSHAREFAIL = 116; 
    public static final byte DELETESUCCESS = 117; 
    public static final byte DELETEFAIL = 118; 
    public static final byte GETALLSUCCESS = 119; 
    public static final byte GETALLFAIL = 120; 
    public static final byte PASSWORDVALID = 121; 
    public static final byte PASSWORDINVALID = 122; 
    public static final byte CLIENTROUTEREQUEST = 60;
    public static final byte SERVERSTARTREQUEST = 61;
    public static final byte SERVERSHAREFILEREQUEST = 123; 
    public static final byte SERVERSHAREFILERESPONSE = 124; 
}